# [START runtime]
runtime: nodejs
env: flex
manual_scaling:
  instances: 1
# [END runtime]
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: mastermind-198210:europe-west2:mastermind